import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
   "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
size = 14

[font.bold]
family = "Fira Code"

[font.italic]
family = "Fira Code"

[font.normal]
family = "Fira Code"
style = "Regular"

[env]
TERM = "xterm-256color"

